# Numpy

Dit is een voorbeeld van numpy

### Stap 1

Als eerste importeren we numpy

In [2]:

import numpy as np



## N dimensionele arrays
2d array (matrix) 

3d array (tensor)

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

### Stap 2

maak een (1d) array met de arange methode en "reshape" deze naar een 3 bij 5 array

>Zie ook dat we in notebook printen zonder print() te hoeven gebruiken.
>
>Dat is alleen met de laatste waarde, als je tussendoor iets wilt printen, moet je wel print() gebruiken

In [5]:

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x




array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Stap 3

Je ziet dat je hier heel makkelijk door ndarrays kunt slicen

In [6]:
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

### Stap 4
met de max methode kun je de max waarde van elke rij in de ndarray berekenen

In [8]:
x.max(axis=1)



array([ 4,  8, 13])

## Statistische bewerkingen

numpy staat ook vol met statistische vewerkingen, zoals de normale distributie.

Hier maken we eerst een generator, en daarmee een array van 2500 willekeurige getallen getrokken uit een normale verdeling.

In [9]:
# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([ 0.04965795, -0.53513435,  1.42315089, ...,  1.25490688,
        0.69534924,  0.0942118 ])

## gemiddelde
We kunnen vervolgens ook  het rekenkunig gemiddelde hiervan berekenen

In [10]:
samples.mean()

np.float64(0.02038885713968398)

## Optellen en vermenigvuldigen van elementen

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b    
c


array([5, 7, 9])

In [12]:
d = a * b    
d

array([ 4, 10, 18])

In [14]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])  # Different shapes
result = a * b
result

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])